services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    hostname: luminessa-backup
    env_file:
      - /opt/syncthing/.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config:/var/syncthing
      - ./data:/sync  # Encrypted data storage
    ports:
      - 22000:22000/tcp   # Sync protocol
      - 22000:22000/udp
      - 21027:21027/udp   # Local discovery
    networks:
      - proxy

networks:
  proxy:
    external: true
