services:
  postgres:
    image: postgres:17.7  # Pin specific version
    container_name: postgres
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # Only accessible from the server itself
    networks:
      - database

networks:
  database:
    external: true

